# Generated by Django 3.1 on 2022-12-07 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=30)),
                ('club_name', models.CharField(max_length=100)),
                ('club_rotary_id', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_no', models.CharField(max_length=100)),
                ('jacket_size', models.CharField(max_length=100)),
                ('participate_in_ryla', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
