# Generated by Django 3.1 on 2022-12-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0005_auto_20221220_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotaractor_or_interactor_or_rotarian', models.CharField(max_length=100)),
                ('auth_token', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=30)),
                ('club_name', models.CharField(max_length=100)),
                ('club_rotary_id', models.CharField(max_length=30)),
                ('club_email_id', models.EmailField(max_length=30)),
                ('parent_club_name', models.CharField(max_length=100)),
                ('presidents_name', models.CharField(max_length=100)),
                ('presidents_contact_no', models.CharField(max_length=100)),
                ('secretary_name', models.CharField(max_length=100)),
                ('secretary_contact_no', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_no', models.CharField(max_length=100)),
                ('jacket_size', models.CharField(max_length=100)),
                ('no_of_participants', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
