# Generated by Django 3.1 on 2022-12-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0006_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='rotary_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
