# Generated by Django 3.1 on 2022-12-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0008_club_payment_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='club_name',
        ),
        migrations.AddField(
            model_name='club',
            name='interactor_club_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='rotaractor_club_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='rotary_club_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
