# Generated by Django 3.1 on 2022-12-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0009_auto_20221220_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='auth_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='blood_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_email_id',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_rotary_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='club',
            name='contact_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='email_id',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='club',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='emergency_contact_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='interactor_club_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='jacket_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='no_of_participants',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='parent_club_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='presidents_contact_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='presidents_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='rotaractor_club_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='rotaractor_or_interactor_or_rotarian',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='rotary_club_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='rotary_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='club',
            name='secretary_contact_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='secretary_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
